### ISSUE TITLE
Relax pins for dependencies (especially calver packages)

### ISSUE THREAD

**Issue by scottyhq** [nsidc/earthdata#65]
Hi @betolink ! Great work here, I'm trying to install earthdata but having a bit of trouble with version pins:

```
Encountered problems while solving:
  - package earthdata-0.1.1a6-pyhd8ed1ab_0 requires s3fs >=2021.8.1,<2022.0.0, but none of the providers can be installed
```

Makes it hard to install earthdata into existing environments with other packages. Perhaps these could be changed to minimum consrtaints (`s3fs >= "^2021.8.1" `)?

**Comment by betolink** [comment]
Hi @scottyhq, yeah I can definitely do that. I'm also working on a couple API changes that I plan to integrate it today/tomorrow. I'll @ you here when this gets done.

**Comment by betolink** [comment]
Hi @scottyhq, I relaxed the dependencies and released v.0.2.0 but the conda-forge recipe is not up to date. You can grab v0.2.0 from pip directly for now.

**Comment by betolink** [comment]
@scottyhq It'd be cool to join as a maintainer, should I open a ticket in the repo or is it somehow an automated process?

I was able to install your environment file with earthdata as a pip dependency but since you're using conda-lock that's a bit tricky I guess. I don't get where the issue is coming from, earthdata has no sat-stac dependency etc. I'll try to update the conda forge recipe if I become a maintainer.

**Comment by scottyhq** [comment]
closed by https://github.com/conda-forge/earthdata-feedstock/pull/6
